server:
  port: 7000

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**
        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/enrollments/**
